[package]
name = "crusty_crypt"
version = "1.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

[profile.release]
strip = true  # Automatically strip symbols from the binary
opt-level = "z"  # Optimize for size
lto = true  # Link-time optimization
codegen-units = 1  # Reduce codegen units to 1
panic = "abort"  # Abort on panic

[package.metadata.cross.target.aarch64-unknown-linux-gnu]
xargo = false
build-std = true
