[package]
name = "crusty_crypt"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

[package.metadata.cross.target.aarch64-unknown-linux-gnu]
xargo = false
build-std = true
