[package]
name = "crusty_chute"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ftp = "3.0.1"
rand = "0.8.3"
chrono = "0.4.19"